l_german:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 group_armor_title: "Gepanzerte Bataillone"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RDiese Vorlage kann nicht gelöscht werden, weil $AMOUNT|H$ Division(en) dabei sind, von dieser Vorlage auf eine andere zu wechseln (d.h. sie warten auf Ausrüstung, die zur neuen Vorlage passt).§!"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Einheit sollte mindestens einen Befehl am Schauplatz haben, um einer beliebigen Gruppe zugewiesen zu werden."

#fixed missing article
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GKlicken§!, um den Einsatzort für diesen Einsatz festzulegen.\n§GRechtsklicken§!, um den Ort zurückzusetzen.\n§YDiese Kolonialvorlage kann nur im Ursprungsland eingesetzt werden!§!"
